version: '2'
services:
  newenergyompweb:
    build:          #镜像构建
      context:  .   #构建镜像时所在的资源路径
      dockerfile: Dockerfile    #构建镜像时需要的dockerfile文件路径
    ports:
      - "5099:8080"     #端口映射
    image: newenergyompweb:v1   #镜像名称和tag
    volumes:
      - "/root/logs/newenergy-omp-web:/usr/local/tomcat/logs"   #挂载日志文件
      
    

